version: "2"

run:
  timeout: 2m
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
  settings:
    errcheck:
      check-type-assertions: true
      check-blank: false
  exclusions:
    rules: []
